### ISSUE TITLE
[Suggestion] Interaction from all players required to start

### ISSUE THREAD

**Issue by MightyW0lf** [Mordrog/RoR2-VoidCellsRequiresAllPlayers#1]
Require all players to interact with the Cell Vent in order to start it. Could be toggleable in the configuration (when toggled off, the current behavior, where all players need to be in the safe zone, would apply).

Goal of this change is to make sure all players are *really* ready (somebody might be still healing and would want others to wait for them to fully heal).

**Comment by Mordrog** [comment]
I am thinking of option to fully regenerate players when they are inside buff area of ​​void cell (before starting stabilization of course).

**Comment by Mordrog** [comment]
Hi, I added option to fully heal players on start of void cell stabilization
